.TH SIC 1 sic-0.0
.SH NAME
sic \- simple irc client
.SH SYNOPSIS
.B sic
.RB [ \-v ]
.SH DESCRIPTION
.B sic
is an extremly fast, small and simple irc client.  It reads commands from
standard input and prints all server output to standard output. It multiplexes
also all channel traffic into one output, that you don't have to switch
different channel buffers, that's actually a feature.
.SH OPTIONS
.TP
.BI \-v
Prints version information to standard output, then exits.
.SH COMMANDS
.TP
.BI /j " #channel/user "
join/query a channel/user
.TP
.BI /l " #channel "
leave a channel/query
.TP
.BI /m " #channel/user msg "
write a message to #channel/user
.TP
.BI /t " topic"
set the channel topic
.TP
Everything which is not a command will simply be posted into the channel or to
the server.
.SH CUSTOMIZATION
.B sic
is customized through editing its source code.  This keeps it fast, secure and
simple. The source code contains the
.I CUSTOMIZE
keyword to highlight relevant portions for customization.
